### PR TITLE
Remove deprecated ugettext import

### PR DESCRIPTION
**Pull request by julianwachholz**
This fixes compatibility for Django 4.0.

### CODE REVIEW

**Comment by knifecake** [comment]
It'd be great if this could be merged! Thanks for the fix!

**Comment by mathiasertl** [comment]
LGTM, thanks.

**Comment by julianwachholz** [comment]
Thanks! I've been using my fork directly so far, this helps. Do you have any plans for a new release on PyPI?

**Comment by mathiasertl** [comment]
Hi @julianwachholz,

First, I wasn't even thinking anyone was using this. Great to hear that there's users of this module!

I just did some other massive updates structurally to bring the project up to modern standards. If you can give the current `main` branch a quick spin and give me feedback, I would release the new version. See `ChangeLog.md` for changes I made.

kr, Mat

**Comment by mathiasertl** [comment]
PS: Does your fork have any other changes?

**Comment by julianwachholz** [comment]
Hey @mathiasertl! I am using this for the relaunch of my [Trivia project](https://triviaroyale.io) and wanted to support the legacy password hashes migrating to Django, so this project fit perfectly. :)

My fork doesn't have any other changes. I will test the current `main` branch in a bit!

**Comment by mathiasertl** [comment]
@julianwachholz any updates?

**Comment by julianwachholz** [comment]
I wanted to check it this weekend but it'll take a bit longer unfortunately because my WSL 2 installation broke with the recent Windows update..

**Comment by julianwachholz** [comment]
@mathiasertl heya! Sorry for the late feedback but everything seems to be working with the latest `main` code!

**Pull request merged**
